version: "3"
services:
  application:
    image: spring-security-jdbc-application
    container_name: "sbsecuritycontainerapp"
    ports:
      - 9000:9000
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql:8.0.36
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=securitymanagement
    volumes:
      - /data/mysql
networks:
  springboot-db-net:
